### ISSUE TITLE
Update Semmle tile to GitHub

### ISSUE THREAD

**Issue by jhutchings1** [microsoft/sarif-website#117]
@lgolding Do you mind patching the SARIF homepage to replace the Semmle link/logo with one to GitHub? Let me know if you need more information from me on this. 🙇🏻

**Comment by lgolding** [comment]
@michaelcfanning FYI.

No problem.

- Do you want to link to `https://github.com`, or to something underneath it?
- Could you please provide me with a 100px x 100px `.png`? I don't know if you want text, or an Octocat, or what.

**Comment by michaelcfanning** [comment]
@jhutchings1, https://securitylab.github.com/tools/codeql?

**Comment by jhutchings1** [comment]
Thanks @lgolding and @michaelcfanning ! 

Let's do https://github.com/features/security, since it's the marketing page that talks about all the things we're doing there. 

I've also attached the invertocat logo, scaled to 100x100. 
![GitHub-Mark-100px](https://user-images.githubusercontent.com/12853539/93822170-a53ceb80-fc14-11ea-839b-bf6bd2cc4a79.png)

**Comment by lgolding** [comment]
Hover text?

**Comment by lgolding** [comment]
Also, perhaps a bit smaller, to leave a bit of a margin? (sorry):
![image](https://user-images.githubusercontent.com/11762653/93822899-c5b97580-fc15-11ea-8750-61864663f17e.png)

**Comment by jhutchings1** [comment]
> Hover text? 

Just `GitHub, Inc.` would work

Here it is at 80px. ![GitHub-Mark-80px](https://user-images.githubusercontent.com/12853539/93824704-ba1b7e00-fc18-11ea-9009-ead5954dc332.png)

**Comment by lgolding** [comment]
Blah. I think it's stretching the image. Will look more closely after my 3:00 meeting. Nothing's ever quite as easy as you hope...

**Comment by jeffersonking** [comment]
I put it on a 100x100 white-background PNG tile just like the others. HTH.
________________________________

**Comment by jeffersonking** [comment]
I put the mark on a 100x100 white-background PNG tile just like the others. I also put the logo on it too. See which one works visually. HTH.

![Github-Mark](https://user-images.githubusercontent.com/3452831/93826458-1fbd3980-fc1c-11ea-8f8c-e73267ee3714.png)
![Github-Logo](https://user-images.githubusercontent.com/3452831/93826462-221f9380-fc1c-11ea-9197-8ef65aa6c4ce.png)

**Comment by lgolding** [comment]
Thanks Jeff, that looks great! So Justin, your choice:

![image](https://user-images.githubusercontent.com/11762653/93827111-7d9e5100-fc1d-11ea-82d1-c2457b17fa04.png)

or

![image](https://user-images.githubusercontent.com/11762653/93827191-a0c90080-fc1d-11ea-9b4f-e2901af754bb.png)

**Comment by jhutchings1** [comment]
The brand guidelines don't say which we should pick, so personal preference: let's ship with the Octocat mark. 😄

**Comment by lgolding** [comment]
Ok. @jeffersonking, stand by for the PR.

**Comment by lgolding** [comment]
@jhutchings1 @michaelcfanning @jeffersonking FYI The change is merged and published to the web site. Thanks @jeffersonking for review and for help with image.
