### ISSUE TITLE
Online validator doesn't report all results

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-website#119]
Given this SARIF file:

[ValidResults.sarif.txt](https://github.com/microsoft/sarif-website/files/5285983/ValidResults.sarif.txt)

the [online validator](http://sarifweb.azurewebsites.net/Validation) reports only 4 results, from 1 rule, even with both checkboxes checked. But the command line validator (correctly) produces many more results:

```
Sarif.Multitool.exe validate
    c:\dev\sarif-sdk\src\Test.UnitTests.Sarif.Converters\TestData\FlawFinderCsv\ExpectedOutputs\ValidResults.sarif
    --pretty-print --force --output ValidResults-validation.sarif --verbose
```

[ValidResults-validation.sarif.txt](https://github.com/microsoft/sarif-website/files/5285985/ValidResults-validation.sarif.txt)

@michaelcfanning FYI

**Comment by lgolding** [comment]
The problem is that the web site runs the validator with `--config github.config.xml`, which it gets from the SARIF SDK. But that config is intended to be used when _the only thing you care about is that GitHub will accept your SARIF_. As such, it _disables_ many of the note-level rules.

The fix is to use a web-site specific configuration file that turns on the GitHub rules without turning off any other rules.

@michaelcfanning FYI

**Comment by lgolding** [comment]
The right thing to do is not to introduce a GitHub configuration that just the web site uses. It's to _fix_ the GitHub configuration in the SDK so that it only turns _on_ the GitHub rules; it doesn't turn _off_ any other rules.

So the work here reduces to: Update to the new SDK once we fix microsoft/sarif-sdk#2089 ("GitHub policy should not turn off any note-level rules").

**Comment by lgolding** [comment]
@michaelcfanning:

It turns out to be a little more complicated. The existing GitHub config file not only turns on the `GH` rules (which is good) and turns off note-level rules (which is bad): it also _elevates_ two rules (from warning and note, respectively) to errors:
```xml
  <Properties Key='SARIF2007.ExpressPathsRelativeToRepoRoot.Options'>
    <!-- Upgraded from Warning. -->
    <Property Key='RuleEnabled' Value='Error' />
  </Properties>

  <Properties Key='SARIF2012.ProvideHelpUris.Options'>
    <!-- Because GitHub displays them if available. -->
    <Property Key='RuleEnabled' Value='Error' />
  </Properties>
```
Here's the problem:

1. If we remove from github.config.xml everything _except_ the `GH` rules, then the online validator won't report `SARIF2007` and `SARIF2012` as errors, even when "GitHub rules" is checked.
2. If we retain in github.config.xml both the GitHub rules and the elevations for `SARIF2007` and `SARIF2012`, then `SARIF2007` and `SARIF2012` will be reported as errors, even when "GitHub rules" is _not_ checked.

One option would be to create two configuration files, allRules.config.xml (which enables the `GH` rules but does nothing else) and github.config.xml (which both enables the GitHub rules and elevates `SARIF2007` and `SARIF2012`). The online validator could re-run the validation with the appropriate configuration as the use checked and unchecked "GitHub rules".

But this is a significant perf penalty (at least a few seconds each time you check the box). The current behavior validates the input file only once, and then just filters the results as you check the boxes. But that won't work because "GitHub rules" not only adds additional rules, it changes the reported level of other rules.

Thoughts?

**Comment by michaelcfanning** [comment]
It is part of the policy to elevate these other rules to errors, and therefore they belong in the GH policy. I think we agree on this, yes? i.e., a policy doesn't strictly align along rule boundaries. A policy shouldn't explicitly alter a rule setting that isn't relevant to the policy concern. 

I don't understand your example of #2. If the GH rules are not checked, then the elevation of the non-GH rules to error shouldn't be applied (because these are packaged in the GH policy). 

I do understand there's a high-level take-away here which is that our policy merging is shaping up to be an order-sensitive operation and it's hard to know how to handle this with check-box driven enabling/disabling. We're lucky here (if I'm correct on all points) that we don't have an actual problem: the 'additional notes' checkbox simply adds the verbose setting to the mix.

**Comment by lgolding** [comment]
Yes, we agree that the two elevations belong in the policy. So let me explain <span>#</span>2.

As the code stands today, when you drop a SARIF file onto the validator, it runs the command
```
sarif validate --verbose --config github.config.xml [several other options]
```
It never runs the `validate` command again for that file. Rather, it simply filters the results from the initial `validate` command as you check and uncheck the check boxes.

By default, both check boxes are unchecked. In particular, the user does _not_ expect to see GitHub-related results.

But since github.config.xml elevates `SARIF2007` and `SARIF2012`, the user will see any results from these rules as errors, which they normally are not. That is my scenario <span>#</span>2.

What _should_ happen is that `SARIF2007` and `SARIF2012` show up as warning and note, respectively, when GitHub results are _not_ selected, and as errors when GitHub results _are_ selected. But to get that experience, we either have to

1. Re-run the validation with a different configuration as the user selects and unselects GitHub rules. This is slow.
OR
2. Hard-code logic into the web site to adjust the viewed levels of those two rules as the user toggles the GitHub rules. This is not maintainable.

That is the problem we need to solve.

**Comment by michaelcfanning** [comment]
This is the standard policy dilemma: policy does not comprise good configuration. Policy is best applied as a filter. That is, the tool generates comprehensive results and the policy is applied after the fact to reduce/rework the results in support of some specific view.

So in an ideal world, we'd process these files and run the superset of rules specified by config/policy (picking up default enabled/disabled states except where explicitly overridden). After this, we would relevel/filter according to the configured failure levels (+verbose setting).

**Comment by lgolding** [comment]
Oh, that is a really nice, concise, mnemonic formulation: _policy does not comprise good configuration_.

What we really need and don't have is an "apply policy to results list" API. This API would both filter results and adjust levels.

I think we should open an issue in the SDK to create that API, and then re-purpose this issue to have the web site do a comprehensive scan and consume the policy API.

Thoughts?

**Comment by michaelcfanning** [comment]
I like this. But our highest concern is to get the web site working. Although a workaround wouldn't be maintainable, as you noted, I think we should prioritize getting the site doing the right thing, even with an imperfect solution. Then let's build the SDK side API as you mention and update the site when we can.

**Comment by lgolding** [comment]
Yes, thanks, I meant to express my concern about the present state of the web site, and the urgency of getting it working properly, in my previous message. I'll do what you suggest.

**Comment by lgolding** [comment]
Good news! The web site doesn't actually display the result's level (although you could argue that it should) in any way. So the "quick fix" requires _only_ a temporary config file that enables the GitHub rules and doesn't disable anything else. The config file doesn't have to elevate any rules, and the web site doesn't need any temporary code to adjust levels. PR to follow in a few minutes.

@michaelcfanning FYI

**Comment by lgolding** [comment]
Ugh. Except that the web site let's you _download_ the validation results SARIF, and there you would see the incorrect levels. So I have to do the post-processing after all.

**Comment by michaelcfanning** [comment]
If the level adjustment is merely from warning to error, I wouldn't get wrapped up in the SARIF level being wrong. Exporting SARIF is not the happy path, viewing the results in the browser is the primary scenario. If the results are elided from the SARIF file entirely (because defaults say they shouldn't be persisted in non-verbose mode), this is more of a concern. Make sense?

**Comment by lgolding** [comment]
It does make sense, and I was hoping you'd say that but didn't want to influence you.

`SARIF2007.ExpressPathsRelativeToRepoRoot` elevates from warning to error, which is fine, but `SARIF2012.ProvideHelpUris` elevates from note to warning.

Let's talk about the elevation of `SARIF2012.ProvideHelpUris`.  A comment in the policy file explains that it's "... because GitHub displays them if available". Is that a good enough reason to elevate it? Even if it _is_ a good enough reason, is it worth the extra temporary code in the web site, and the delay in making the temporary fix, for this sake of _this_ rule?

**Comment by lgolding** [comment]
Oh! And remember that the web site does run the validator with `--verbose`, so the 2012s _will_ be exported. So by your reasoning we do not need to do any post-processing. I'll raise the PR as is.

**Comment by lgolding** [comment]
... and it just never ends. The validator _will_ export a SARIF file with note-level results.  But if the viewers followed the guidance in the [document](https://github.com/microsoft/sarif-tutorials/blob/users/lgolding/perceived-severity/docs/Displaying-results-in-a-viewer.md) I sent for review (to hide note-level results by default) then the user wouldn't see them, which would be bad.

But today, at least, both the VS and VS Code viewers display note-level results by default. The web site should be well and truly fixed, using a proper policy-based post-processing API from the SDK, before the viewers catch on.

**Comment by michaelcfanning** [comment]
Will it help if I just make a call? Please add one-off support to elevate those two rules to errors in the event that the GH rules are enabled.

**Comment by lgolding** [comment]
Approved by @jeffersonking, merging.
