### ISSUE TITLE
Sarif validator returning 404 when trying to validate a file

### ISSUE THREAD

**Issue by felipe-avelar** [microsoft/sarif-website#131]
When I upload any .sarif file, the upload boxes shows me an alert that "An unknown error occurred." and a red error label on file's drop.
I tried with the following sarif code:
```
{
  "version": "2.1.0",
  "$schema": "http://json.schemastore.org/sarif-2.1.0-rtm.4",
  "runs": [
    {
      "tool": {
        "driver": {
          "name": "ESLint",
          "informationUri": "https://eslint.org",
          "rules": [
            {
              "id": "no-unused-vars",
              "shortDescription": {
                "text": "disallow unused variables"
              },
              "helpUri": "https://eslint.org/docs/rules/no-unused-vars",
              "properties": {
                "category": "Variables"
              }
            }
          ]
        }
      },
      "artifacts": [
        {
          "location": {
            "uri": "file:///C:/dev/sarif/sarif-tutorials/samples/Introduction/simple-example.js"
          }
        }
      ],
      "results": [
        {
          "level": "error",
          "message": {
            "text": "'x' is assigned a value but never used."
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "file:///C:/dev/sarif/sarif-tutorials/samples/Introduction/simple-example.js",
                  "index": 0
                },
                "region": {
                  "startLine": 1,
                  "startColumn": 5
                }
              }
            }
          ],
          "ruleId": "no-unused-vars",
          "ruleIndex": 0
        }
      ]
    }
  ]
}
```

**Comment by eddynaka** [comment]
Hello,

I'm taking a look right now!
thanks for reporting!

**Comment by eddynaka** [comment]
Fixed. Can you try again? Reopen if that does not work.
thank you

**Comment by felipe-avelar** [comment]
I tried with the same file and the validation was complete, but now it freezes after completing the validation with this error when opening console:

```
Uncaught TypeError: Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.
    at Object.success (Validation:491)
    at u (jquery-3.3.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-3.3.1.min.js:2)
    at k (jquery-3.3.1.min.js:2)
    at XMLHttpRequest.<anonymous> (jquery-3.3.1.min.js:2)
```

At Validation:49

**Comment by eddynaka** [comment]
@felipe-avelar, are u facing with the sarif above?

**Comment by felipe-avelar** [comment]
> @felipe-avelar, are u facing with the sarif above?

Yes

**Comment by eddynaka** [comment]
> > @felipe-avelar, are u facing with the sarif above?
> 
> Yes

Just tested in the latest edge chromium and google chrome. Both worked.

Try to clean cache and refresh.

**Comment by eddynaka** [comment]
![image](https://user-images.githubusercontent.com/16199012/105837995-3e5a8500-5fae-11eb-9bfd-38faf82c1b9e.png)

**Comment by felipe-avelar** [comment]
@eddynaka I successfully validate when I browse for the file.

I think the problem is when dropping file to be validated. So I think this issue is closed :)

**Comment by eddynaka** [comment]
> @eddynaka I successfully validate when I browse for the file.
> 
> I think the problem is when dropping file to be validated. So I think this issue is closed :)

I see. I will take a look at this today!

**Comment by eddynaka** [comment]
@felipe-avelar, drop is working :)

clean cache and try again, pls!

thank you

**Comment by felipe-avelar** [comment]
Everything is working, thanks a lot 😄
